name: CI
# Force CI re-run after adding package-lock.json

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Build project
      run: npm run build
      
    - name: Check for cruft
      run: |
        # Ensure no Python files were accidentally introduced
        if find . -name "*.py" -not -path "./node_modules/*" | grep -q .; then
          echo "❌ Python files found - this is a TypeScript project"
          exit 1
        fi
        
        # Ensure no Docker files (not needed for this CLI tool)
        if find . -name "Dockerfile*" -o -name "docker-compose*" | grep -q .; then
          echo "❌ Docker files found - unnecessary for CLI tool"
          exit 1
        fi
        
        # Ensure no unused dependencies
        npm audit --audit-level=moderate
        
        echo "✅ No cruft detected"

  coverage:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate coverage report
      run: npm test -- --coverage
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3